In [5]:
import numpy as np

In [11]:
letter = 'abcdefg'

In [15]:
text = 'abcdefefgabcdgabcgaefgabdefgabccdefgabcdabcde'

In [12]:
POS = {l: i for i, l in enumerate(letter)}
POS

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6}

In [13]:
matrix = np.zeros((len(letter), len(letter)))
matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
for i, j in zip(text[:-1], text[1:]):
    matrix[POS[i], POS[j]] +=1
    
matrix

array([[0., 7., 0., 0., 1., 0., 0.],
       [0., 0., 6., 1., 0., 0., 0.],
       [0., 0., 1., 5., 0., 0., 1.],
       [1., 0., 0., 0., 4., 0., 1.],
       [0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 1., 0., 4.],
       [6., 0., 0., 0., 0., 0., 0.]])

In [17]:
matrix_1 = (matrix / matrix.sum(axis=1)[:, None])

In [19]:
matrix

array([[0., 7., 0., 0., 1., 0., 0.],
       [0., 0., 6., 1., 0., 0., 0.],
       [0., 0., 1., 5., 0., 0., 1.],
       [1., 0., 0., 0., 4., 0., 1.],
       [0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 1., 0., 4.],
       [6., 0., 0., 0., 0., 0., 0.]])

In [20]:
matrix.sum(axis=1)

array([8., 7., 7., 6., 5., 5., 6.])

In [21]:
matrix/matrix.sum(axis=1)

array([[0.        , 1.        , 0.        , 0.        , 0.2       ,
        0.        , 0.        ],
       [0.        , 0.        , 0.85714286, 0.16666667, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.14285714, 0.83333333, 0.        ,
        0.        , 0.16666667],
       [0.125     , 0.        , 0.        , 0.        , 0.8       ,
        0.        , 0.16666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.2       ,
        0.        , 0.66666667],
       [0.75      , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [27]:
matrix.sum(axis=1)[:, None]

array([[8.],
       [7.],
       [7.],
       [6.],
       [5.],
       [5.],
       [6.]])

In [18]:
matrix_1

array([[0.        , 0.875     , 0.        , 0.        , 0.125     ,
        0.        , 0.        ],
       [0.        , 0.        , 0.85714286, 0.14285714, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.14285714, 0.71428571, 0.        ,
        0.        , 0.14285714],
       [0.16666667, 0.        , 0.        , 0.        , 0.66666667,
        0.        , 0.16666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.2       ,
        0.        , 0.8       ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [29]:
import pandas as pd

In [30]:
df = pd.DataFrame(matrix_1, index=(c for c in letter), columns=(c for c in letter))
df

a      b         c         d         e    f         g
a  0.000000  0.875  0.000000  0.000000  0.125000  0.0  0.000000
b  0.000000  0.000  0.857143  0.142857  0.000000  0.0  0.000000
c  0.000000  0.000  0.142857  0.714286  0.000000  0.0  0.142857
d  0.166667  0.000  0.000000  0.000000  0.666667  0.0  0.166667
e  0.000000  0.000  0.000000  0.000000  0.000000  1.0  0.000000
f  0.000000  0.000  0.000000  0.000000  0.200000  0.0  0.800000
g  1.000000  0.000  0.000000  0.000000  0.000000  0.0  0.000000